# Basic Vector and Matrix Operation with Numpy.

Complete the following Tasks:

1. Initialize an empty array with size 2X2.

In [4]:
import numpy as np

# Initialize an empty array with size 2x2 with integer data type
empty_array = np.empty((2, 2), dtype=int)

# Fill the array with single-digit numbers (0-9)
empty_array = np.random.randint(0, 10, size=(2, 2))

# Print the array
print(empty_array)

[[4 0]
 [6 1]]


2. Initialize an all one array with size 4X2.

In [5]:
import numpy as np

# Initialize an all-one array with size 4x2
all_one_array = np.ones((4, 2))

# Print the array
print(all_one_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [6]:
import numpy as np

# Define the shape, type, and fill value
shape = (3, 2)  # Example shape: 3 rows, 2 columns
data_type = int  # Example type: integer
fill_value = 7  # Example fill value

# Create the array using np.full
filled_array = np.full(shape, fill_value, dtype=data_type)

# Print the array
print(filled_array)

[[7 7]
 [7 7]
 [7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [7]:
import numpy as np

# Example given array
given_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

# Create a new array of zeros with the same shape and type as given_array
zeros_array = np.zeros_like(given_array)

# Print the zeros_array
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [8]:
import numpy as np

# Example given array
given_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

# Create a new array of ones with the same shape and type as given_array
ones_array = np.ones_like(given_array)

# Print the ones_array
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [10]:
import numpy as np

# Existing list
new_list = [1, 2, 3, 4]

# Convert the list to a NumPy array
numpy_array = np.array(new_list)

# Print the NumPy array
print(numpy_array)

[1 2 3 4]


# Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [11]:
import numpy as np

# Create an array with values ranging from 10 to 49
array_range = np.arange(10, 50)

# Print the array
print(array_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [12]:
import numpy as np

# Create a 1D array with values ranging from 0 to 8
array_1d = np.arange(9)

# Reshape the 1D array into a 3x3 matrix
matrix_3x3 = array_1d.reshape((3, 3))

# Print the matrix
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [13]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

# Print the matrix
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [14]:
import numpy as np

# Create a random array of size 30
random_array = np.random.random(30)

# Find the mean of the array
mean_value = random_array.mean()

# Print the mean
print(mean_value)

0.4573164869205191


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [15]:
import numpy as np

# Create a 10x10 array with random values
random_array = np.random.rand(10, 10)

# Find the minimum and maximum values
min_value = random_array.min()
max_value = random_array.max()

# Print the minimum and maximum values
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.00010965174840849023
Maximum value: 0.9951084447803191


6. Create a zero array of size 10 and replace 5th element with 1.

In [16]:
import numpy as np

# Create a zero array of size 10
zero_array = np.zeros(10)

# Replace the 5th element (index 4) with 1
zero_array[4] = 1

# Print the modified array
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [17]:
import numpy as np

# Define the array
arr = np.array([1, 2, 0, 0, 4, 0])

# Reverse the array
reversed_arr = arr[::-1]

# Print the reversed array
print(reversed_arr)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [18]:
import numpy as np

# Define the shape of the array (e.g., 5x5)
shape = (5, 5)

# Create an array filled with ones
array = np.ones(shape, dtype=int)

# Set the inner elements to 0
array[1:-1, 1:-1] = 0

# Print the array
print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [19]:
import numpy as np

# Create an 8x8 matrix filled with zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Fill with checkerboard pattern
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

# Print the matrix
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Array Operations:

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:

1. Add the two array.

In [20]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Add the two arrays
result = np.add(x, y)

# Print the result
print(result)


[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [21]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Subtract the two arrays
result = np.subtract(x, y)

# Print the result
print(result)


[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [22]:
import numpy as np

# Define the array
x = np.array([[1, 2], [3, 5]])

# Multiply the array by an integer (e.g., 3)
result = x * 3

# Print the result
print(result)


[[ 3  6]
 [ 9 15]]


4. Find the square of each element of the array

In [23]:
import numpy as np

# Define the array
x = np.array([[1, 2], [3, 5]])

# Find the square of each element
result = np.square(x)

# Print the result
print(result)


[[ 1  4]
 [ 9 25]]


5. Find the dot product

v(and)w

In [24]:
import numpy as np

# Define the vectors
v = np.array([9, 10])
w = np.array([11, 12])

# Dot product
result = np.dot(v, w)

# Print the result
print(result)


219


x(and)v

In [25]:
import numpy as np

# Define the array and vector
x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

# Dot product
result = np.dot(x, v)

# Print the result
print(result)


[29 77]


x(and)y.

In [26]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Dot product
result = np.dot(x, y)

# Print the result
print(result)


[[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

x(and)y along row

In [27]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Concatenate along rows
result = np.concatenate((x, y), axis=0)

# Print the result
print(result)


[[1 2]
 [3 5]
 [5 6]
 [7 8]]


v(and)w along column.

In [28]:
import numpy as np

# Define the vectors
v = np.array([9, 10])
w = np.array([11, 12])

# Concatenate along columns
result = np.vstack((v, w)).T

# Print the result
print(result)


[[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [30]:
import numpy as np

# Define the array and vector
x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

# Attempt to concatenate
result = np.concatenate((x, v), axis=0)

# Print the result
print(result)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

The error arise because x is a 2D array with shape (2,2), while v is a 1D array with shape (2,). NumPy cannot concatenate them directly because of different dimensions.
Reshapeing  v as a row vector ((1,2)) or a column vector ((2,1)) before concatenation will fix this issue.

# Matrix Operations:

For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:

1. Prove A.A−1 = I.

In [39]:
import numpy as np

# Define matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
A_inv = np.linalg.inv(A)

# Calculate the product of A and its inverse
identity_matrix = np.dot(A, A_inv)

# Print the result
print(identity_matrix)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ̸= BA.

In [40]:
import numpy as np

# Define matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
# Calculate AB
AB = np.dot(A, B)

# Calculate BA
BA = np.dot(B, A)

# Print the results
print("AB:")
print(AB)
print("\nBA:")
print(BA)

# Check if AB is not equal to BA
print("\nIs AB not equal to BA?", not np.array_equal(AB, BA))

AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

Is AB not equal to BA? True


3. Prove (AB)

T = BTAT

In [41]:
import numpy as np

# Define matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
# Calculate (AB)T
AB_transpose = np.transpose(np.dot(A, B))

# Calculate BTAT
B_transpose_A_transpose = np.dot(np.transpose(B), np.transpose(A))

# Print the results
print("(AB)T:")
print(AB_transpose)
print("\nBTAT:")
print(B_transpose_A_transpose)

# Check if (AB)T is equal to BTAT
print("\nIs (AB)T equal to BTAT?", np.array_equal(AB_transpose, B_transpose_A_transpose))

(AB)T:
[[23 51]
 [13 29]]

BTAT:
[[23 51]
 [13 29]]

Is (AB)T equal to BTAT? True


# Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}\

In [44]:
import numpy as np

# Coefficient matrix
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constant terms
B = np.array([-1, -3, 9])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X by multiplying A_inv with B
X = np.dot(A_inv, B)

# Print the solution
print("Solution:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])

Solution:
x = 2.0
y = 1.0
z = -2.0


Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [47]:
import numpy as np

# Coefficient matrix
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constant terms
B = np.array([-1, -3, 9])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X by multiplying A_inv with B
X = np.dot(A_inv, B)

# Print the solution
print("Solution:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])



Solution:
x = 2.0
y = 1.0
z = -2.0


# Experiment: How Fast is Numpy?

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [48]:
import time
import numpy as np

# Create two lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

# Element-wise addition using Python lists
start_time = time.time()
result_list = [x + y for x, y in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken using Python lists: {list_time:.6f} seconds")

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000)

# Element-wise addition using NumPy arrays
start_time = time.time()
result_array = array1 + array2
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken using NumPy arrays: {array_time:.6f} seconds")

# Compare the execution times
print(f"\nNumPy is {list_time / array_time:.2f} times faster than Python lists for this operation.")

Time taken using Python lists: 0.092062 seconds
Time taken using NumPy arrays: 0.011978 seconds

NumPy is 7.69 times faster than Python lists for this operation.


2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [49]:
import time
import numpy as np

# Create two lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

# Element-wise multiplication using Python lists
start_time = time.time()
result_list = [x * y for x, y in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken using Python lists: {list_time:.6f} seconds")

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000)

# Element-wise multiplication using NumPy arrays
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken using NumPy arrays: {array_time:.6f} seconds")

# Compare the execution times
print(f"\nNumPy is {list_time / array_time:.2f} times faster than Python lists for this operation.")

Time taken using Python lists: 0.109840 seconds
Time taken using NumPy arrays: 0.006459 seconds

NumPy is 17.01 times faster than Python lists for this operation.


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays,

In [50]:
import time
import numpy as np

# Create two lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

# Dot product using Python lists
start_time = time.time()
result_list = sum(x * y for x, y in zip(list1, list2))
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken using Python lists: {list_time:.6f} seconds")

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000)

# Dot product using NumPy arrays
start_time = time.time()
result_array = np.dot(array1, array2)
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken using NumPy arrays: {array_time:.6f} seconds")

# Compare the execution times
print(f"\nNumPy is {list_time / array_time:.2f} times faster than Python lists for this operation.")

Time taken using Python lists: 0.224039 seconds
Time taken using NumPy arrays: 0.005921 seconds

NumPy is 37.84 times faster than Python lists for this operation.
